import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

// auth
import AuthProvider from './context/AuthProvider'

// components
import { SideMenu } from '@/components/Side Menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-row w-screen h-full'>

        <AuthProvider>
          <SideMenu />
          <div className='w-full'>{children}</div>
        </AuthProvider>

      </body>
    </html>
  )
}
